name: test

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
  test:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false

      matrix:
        gemfile:
          - gemfiles/rails_7.gemfile
          - gemfiles/rails_8.gemfile
          - gemfiles/rails_edge.gemfile

        ruby:
          - 2.7.2
          - 3.1.7
          - 3.3.4

        exclude:
          - ruby: 2.7.2
            gemfile: gemfiles/rails_8.gemfile
          - ruby: 2.7.2
            gemfile: gemfiles/rails_edge.gemfile
          - ruby: 3.0.0
            gemfile: gemfiles/rails_8.gemfile
          - ruby: 3.0.0
            gemfile: gemfiles/rails_edge.gemfile

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 11

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          bundler: latest

      - name: Run tests
        run: |
          bundle exec rake spec
        continue-on-error: ${{ matrix.gemfile == 'gemfiles/rails_edge.gemfile' }}
